"""
english_seed.py
Hand-authored English seed corpus (the free tier). Real words, real clues,
every clue written to pass the validation harness (no answer/stem leakage).

This is a SEED, not the 100x100 target. It exists to make the game runnable today
and to give the validator real input. Scaling to 100 groups x 100 words is the job
of pipeline/generate_clues.py against your own inference endpoint.
"""

# theme_slug: (Human label, [(surface, clue), ...])
SEED = {
    "cinema": ("Cinema", [
        ("director", "Person who guides how a film is made"),
        ("script", "Written text of dialogue and action"),
        ("scene", "A single continuous piece of the story"),
        ("villain", "The antagonist working against the hero"),
        ("sequel", "A follow-up to an earlier story"),
        ("trailer", "Short promotional preview shown before release"),
        ("subtitle", "Translated text along the bottom of the picture"),
        ("premiere", "First public showing of a movie"),
        ("cameo", "Brief appearance by a famous face"),
        ("montage", "Quick sequence compressing time"),
        ("score", "Original orchestral music written for a film"),
        ("plot", "The chain of events in a narrative"),
        ("reel", "Spool that once carried the celluloid"),
        ("usher", "Person who shows you to your seat"),
    ]),
    "literature": ("Literature", [
        ("novel", "Long work of prose fiction"),
        ("poet", "Writer who works in verse"),
        ("chapter", "A numbered division of a book"),
        ("metaphor", "Saying one thing is another for effect"),
        ("preface", "Author's note before the main text"),
        ("fable", "Short tale with a moral, often using animals"),
        ("stanza", "A grouped set of lines in a poem"),
        ("memoir", "An account of one's own life"),
        ("satire", "Mockery used to expose folly"),
        ("epic", "Grand heroic narrative of great length"),
        ("genre", "A category of artistic work"),
        ("prose", "Ordinary written language, not verse"),
    ]),
    "music": ("Music", [
        ("melody", "A memorable sequence of pitches"),
        ("rhythm", "The pattern of beats in time"),
        ("chord", "Several notes sounded together"),
        ("tempo", "How fast a piece is played"),
        ("octave", "The gap between a note and its double"),
        ("lyric", "The words sung in a song"),
        ("encore", "Extra piece after loud applause"),
        ("ballad", "A slow, often sentimental song"),
        ("treble", "The higher range of pitches"),
        ("verse", "A repeating section between choruses"),
        ("anthem", "A rousing song of belonging"),
    ]),
    "geography": ("Geography", [
        ("island", "Land surrounded by water"),
        ("plateau", "Raised area of flat ground"),
        ("estuary", "Where a river meets the tide"),
        ("desert", "Arid region with little rainfall"),
        ("glacier", "Slow river of ancient ice"),
        ("isthmus", "Narrow neck of land joining two larger ones"),
        ("canyon", "Deep gorge cut by a river"),
        ("delta", "Fan of sediment at a river's mouth"),
        ("strait", "Narrow channel between two seas"),
        ("summit", "The highest point of a peak"),
        ("tundra", "Treeless plain of the frozen north"),
    ]),
    "cooking": ("Cooking", [
        ("simmer", "Cook gently just below boiling"),
        ("knead", "Work dough with the hands"),
        ("whisk", "Beat air into eggs or cream"),
        ("marinate", "Soak food to flavour it before cooking"),
        ("garnish", "Decorative finish on a plate"),
        ("braise", "Cook slowly in a little liquid"),
        ("grate", "Shred cheese against sharp holes"),
        ("season", "Add salt, pepper and the like"),
        ("sieve", "Mesh tool that separates fine from coarse"),
        ("ladle", "Deep spoon for serving soup"),
    ]),
    "science": ("Science", [
        ("atom", "Smallest unit of an element"),
        ("gravity", "Force that pulls masses together"),
        ("neuron", "A single nerve cell"),
        ("enzyme", "Protein that speeds a reaction"),
        ("orbit", "Curved path of one body around another"),
        ("photon", "A particle of light"),
        ("vector", "Quantity with size and direction"),
        ("isotope", "Variant of an element by neutron count"),
        ("plasma", "The fourth state of matter"),
        ("entropy", "Measure of disorder in a system"),
    ]),
    "animals": ("Animals", [
        ("otter", "Playful river mammal that floats on its back"),
        ("falcon", "Swift bird of prey"),
        ("badger", "Striped burrowing nocturnal digger"),
        ("salmon", "Fish that swims upstream to spawn"),
        ("lynx", "Wild cat with tufted ears"),
        ("heron", "Tall wading bird with a dagger beak"),
        ("beaver", "Rodent that builds dams"),
        ("magpie", "Black-and-white bird that hoards shiny things"),
        ("toad", "Warty amphibian of dry land"),
        ("stoat", "Small fierce hunter that turns white in winter"),
    ]),
    "weather": ("Weather", [
        ("drizzle", "Very light, fine rain"),
        ("blizzard", "Violent snowstorm with high wind"),
        ("humid", "Heavy with moisture in the air"),
        ("thunder", "The crash that follows a flash"),
        ("frost", "Thin ice that forms on cold surfaces"),
        ("gale", "A very strong wind"),
        ("mist", "Thin cloud at ground level"),
        ("hail", "Pellets of ice falling from the sky"),
        ("breeze", "A light, gentle wind"),
    ]),
    "tools": ("Tools", [
        ("hammer", "Strikes nails into wood"),
        ("chisel", "Sharp blade for carving by hand"),
        ("wrench", "Grips and turns a bolt"),
        ("pliers", "Pincers for gripping small parts"),
        ("clamp", "Holds two pieces firmly together"),
        ("drill", "Bores round holes"),
        ("level", "Tells you if a surface is true"),
        ("rasp", "Coarse file for shaping wood"),
        ("anvil", "Heavy block a smith hammers on"),
    ]),
    "transport": ("Transport", [
        ("ferry", "Boat that carries people across water on a route"),
        ("tram", "Street vehicle running on rails"),
        ("rudder", "Steers a vessel from the stern"),
        ("cargo", "Goods carried by a vehicle"),
        ("anchor", "Drops to hold a ship in place"),
        ("cabin", "Enclosed space for crew or passengers"),
        ("freight", "Bulk goods moved for trade"),
        ("saddle", "Seat fixed to a horse or bike"),
        ("hangar", "Large shed that shelters aircraft"),
    ]),
    "emotions": ("Emotions", [
        ("dread", "Deep fear of what is coming"),
        ("relief", "Ease after worry lifts"),
        ("envy", "Resentful longing for what others have"),
        ("pride", "Satisfaction in one's achievements"),
        ("grief", "Deep sorrow after a loss"),
        ("awe", "Wonder mixed with respect"),
        ("spite", "Petty desire to hurt another"),
        ("yearn", "To ache with longing"),
    ]),
    "time": ("Time", [
        ("decade", "A span of ten years"),
        ("dusk", "The dim light as day ends"),
        ("epoch", "A notable stretch of history"),
        ("annual", "Happening once each year"),
        ("eve", "Night just before a holiday"),
        ("noon", "The middle of the day"),
        ("delay", "A postponement to later"),
        ("dawn", "First light of morning"),
    ]),
    "astronomy": ("Astronomy", [
        ("comet", "Icy traveller with a glowing tail"),
        ("galaxy", "Vast island of stars"),
        ("eclipse", "When one body hides another's light"),
        ("crater", "Bowl-shaped dent left by an impact"),
        ("nebula", "Cloud of gas where stars are born"),
        ("meteor", "Streak of light from a falling rock"),
        ("lunar", "Relating to our nearest neighbour in the sky"),
        ("solar", "Relating to the star at our centre"),
        ("cosmos", "Everything that exists, taken as a whole"),
        ("pulsar", "Rapidly spinning collapsed star sending beams"),
        ("planet", "World that circles a star"),
    ]),
    "birds": ("Birds", [
        ("sparrow", "Small brown garden chirper"),
        ("eagle", "Large raptor and national emblem"),
        ("penguin", "Flightless bird of the cold south"),
        ("raven", "Large black corvid of myth"),
        ("swan", "Graceful white waterfowl with a long neck"),
        ("owl", "Nocturnal hunter that hoots"),
        ("robin", "Garden bird with a red breast"),
        ("finch", "Small seed-eating songbird"),
        ("gull", "Coastal scavenger that cries overhead"),
        ("wren", "Tiny bird with a cocked tail"),
        ("hawk", "Sharp-eyed daytime bird of prey"),
    ]),
    "plants": ("Plants and Trees", [
        ("willow", "Tree that weeps over riverbanks"),
        ("fern", "Feathery plant that spreads by spores"),
        ("moss", "Soft green carpet on damp stone"),
        ("birch", "Pale-barked northern tree"),
        ("ivy", "Climbing evergreen that clings to walls"),
        ("maple", "Tree whose sap gives syrup"),
        ("thorn", "Sharp point on a stem"),
        ("petal", "Coloured leaf of a flower"),
        ("oak", "Mighty tree bearing acorns"),
        ("vine", "Trailing or climbing woody stem"),
        ("bloom", "A flower in full open glory"),
    ]),
    "sea": ("Sea and Ocean", [
        ("tide", "Daily rise and fall of the water"),
        ("coral", "Reef built by tiny living polyps"),
        ("wave", "Moving ridge on the surface"),
        ("shore", "Where land meets the water"),
        ("current", "Steady flow within the water"),
        ("harbour", "Sheltered place for boats"),
        ("abyss", "The deepest, darkest waters"),
        ("kelp", "Long brown seaweed forming forests"),
        ("pearl", "Gem grown inside a shell"),
        ("reef", "Ridge of rock or coral near the surface"),
        ("buoy", "Floating marker that warns or guides"),
    ]),
    "clothing": ("Clothing", [
        ("jacket", "Short coat for the upper body"),
        ("collar", "Band that sits around the neck"),
        ("sleeve", "Part that covers the arm"),
        ("button", "Small disc that fastens a shirt"),
        ("scarf", "Cloth wound around the neck for warmth"),
        ("glove", "Covering for the hand and fingers"),
        ("boot", "Sturdy footwear reaching the ankle"),
        ("belt", "Strap worn around the waist"),
        ("hood", "Head covering attached to a coat"),
        ("denim", "Sturdy cotton twill of jeans"),
        ("cuff", "Folded end of a sleeve"),
    ]),
    "buildings": ("Buildings", [
        ("tower", "Tall narrow structure rising high"),
        ("bridge", "Span that crosses a gap"),
        ("castle", "Fortified noble residence"),
        ("chapel", "Small place of worship"),
        ("dome", "Rounded vault forming a roof"),
        ("pillar", "Upright post bearing weight"),
        ("attic", "Room just below the roof"),
        ("cellar", "Storage room below ground"),
        ("spire", "Pointed top of a church"),
        ("balcony", "Platform projecting from an upper floor"),
        ("gable", "Triangular upper part of a wall"),
    ]),
    "materials": ("Materials", [
        ("copper", "Reddish conductive metal"),
        ("iron", "Heavy magnetic metal that rusts"),
        ("silver", "Shiny precious white metal"),
        ("bronze", "Alloy of copper and tin"),
        ("marble", "Polished stone for sculpture"),
        ("timber", "Wood prepared for building"),
        ("granite", "Hard speckled igneous rock"),
        ("amber", "Fossilised tree resin"),
        ("brass", "Yellow alloy of copper and zinc"),
        ("steel", "Strong alloy of iron and carbon"),
        ("glass", "Transparent solid made from melted sand"),
    ]),
    "games": ("Games and Play", [
        ("puzzle", "Problem solved for amusement"),
        ("dice", "Cubes rolled for a number"),
        ("chess", "Board game of kings and pawns"),
        ("riddle", "Question posed as a teasing test"),
        ("token", "Piece moved around a board"),
        ("bishop", "Diagonal-moving chess piece"),
        ("wager", "A bet placed on an outcome"),
        ("maze", "Network of winding paths to escape"),
        ("domino", "Tile marked with two sets of spots"),
        ("arcade", "Hall of coin-fed amusements"),
        ("joker", "Wild card or court jester"),
    ]),
    "mythology": ("Mythology", [
        ("dragon", "Fire-breathing winged beast of legend"),
        ("oracle", "One who foretells through the gods"),
        ("titan", "Giant elder god of old myth"),
        ("nymph", "Minor nature spirit in female form"),
        ("quest", "Heroic journey toward a goal"),
        ("omen", "A sign of what is to come"),
        ("curse", "A spell wishing harm"),
        ("shrine", "Holy place dedicated to a deity"),
        ("mortal", "A being destined to die"),
        ("relic", "Sacred object left from the past"),
        ("fate", "The destiny one cannot escape"),
    ]),
    "body": ("The Body", [
        ("elbow", "Joint at the middle of the arm"),
        ("spine", "Column of bones down the back"),
        ("pupil", "Dark opening at the eye's centre"),
        ("ankle", "Joint between leg and foot"),
        ("tendon", "Cord that ties muscle to bone"),
        ("lung", "Organ that draws in air"),
        ("thumb", "Short opposable digit"),
        ("liver", "Organ that filters the blood"),
        ("palm", "Inner surface of the hand"),
        ("wrist", "Joint between hand and arm"),
        ("rib", "Curved bone guarding the chest"),
    ]),
}
